remote_theme: github-profile-achievements/jekyll-theme

title: Lista completa de todas las insignias y logros del perfil de GitHub
description: Lista completa de todas las insignias y logros del perfil de GitHub
permalinks: pretty

lang: es
logo_url: https://avatars.githubusercontent.com/u/117988194?s=200&v=4

# Navbar
navbar_link_text: Logros del perfil de GitHub en otros idiomas
navbar_button_text: Esta página en GitHub
